### PR TITLE
Update osu!lazer version and... stuff? (remaster branch)

### PR DESCRIPTION
**Pull request by Speykious**
Hello! I wanted to let you know that I really like this project, and that I'd really like to contribute to it in some way.

I especially like the remaster that you're doing. I've actually been playing it for at least 2 weeks after compiling it myself, but it just wouldn't work with the latest version.
Luckily, I managed to find a way to make it work again for the latest version of `ppy.osu.Game`, but also somehow restore Autoplay functionality! (I think it was because of `User` now being `APIUser`.)

However, one _big_ thing that you'll notice in the changes I've made is... well... the formatting. I ran `dotnet format` (see [dotnet format command page](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-format)) on the entire repo, and basically, nothing was written in standard .NET syntax... I mean it's OK, everyone can write code how they want lol. Though to me it was really confusing, so I just formatted it to see what I could do, and I didn't think I would make a pull request - but now I want to contribute! I don't know if I should revert the formatting or if I should suggest to use this one... 😅

Not to mention, I just realized that I left my VSCode debugging files in there, though leaving them there could be useful to other VSCode contributors.

Maybe a better solution would be to create a `.editorconfig` file for more precisely defined formatting rules. Like, idk, maybe you don't like having opening braces on their own lines or something?

Let me know what you think. :)

### CODE REVIEW

**Comment by Flutterish** [comment]
Im glad you enjoy the mode, though the 'newest' version, the one Im working on is the 'remaster-editor' branch. The main mode is not changed much in it, but it reworks a bit of the project structure and adds a WIP editor. I cant merge it before making the editor itself mostly complete, but if you want to contribute, you should work off of the changes made on that branch. If you want to talk about what I could use help with or the project in general, you can message me on discord @Perigee#6747.

As per the formatting, I disagree with any sort of standardised formatting style enforced on a codebase. While it is true that having the same style everywhere is nice and improves ease of reading somewhat, the way you format code is your 'signature' and a human, especially with reviewers will make the format readable. Whether you put extra blank lines, whitespace or where you put your brackets really makes no difference and only serves to annoy you that the editor forces arbitrary rules on the way you write.

**Comment by Speykious** [comment]
Thank you for your feedback! I'll look into the remaster-editor branch and see how stuff is going there.

It's OK to use your own standard for formatting. What I would suggest then is to still use a `.editorconfig` file. You'll be able to specify the rules there, and your editor will comply with your preferences. :)

**Comment by Flutterish** [comment]
> (unless I misunderstood something?)

Every programmer should be allowed to write in their own style, with no standard config. However that style should be reviewed for readability when a pull is made. I see the benefits behind having all code from everyone be the same style, but I dont think it outweighs the benefits of having your own style.
(oh, and if you were talking about me having a personal `.editorconfig` file, I have a global config for my style rules)

**Comment by Speykious** [comment]
I'll close this PR and make a new one on `remaster-editor`.

**Pull request closed without merging**
